// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: app_settings.sql

package db

import (
	"context"
)

const deleteAppSetting = `-- name: DeleteAppSetting :exec
DELETE FROM app_settings
WHERE key = ?
`

func (q *Queries) DeleteAppSetting(ctx context.Context, key string) error {
	_, err := q.db.ExecContext(ctx, deleteAppSetting, key)
	return err
}

const getAppSetting = `-- name: GetAppSetting :one
SELECT key, value, updated_at
FROM app_settings
WHERE key = ? LIMIT 1
`

func (q *Queries) GetAppSetting(ctx context.Context, key string) (AppSetting, error) {
	row := q.db.QueryRowContext(ctx, getAppSetting, key)
	var i AppSetting
	err := row.Scan(&i.Key, &i.Value, &i.UpdatedAt)
	return i, err
}

const listAppSettings = `-- name: ListAppSettings :many
SELECT key, value, updated_at
FROM app_settings
ORDER BY key ASC
`

func (q *Queries) ListAppSettings(ctx context.Context) ([]AppSetting, error) {
	rows, err := q.db.QueryContext(ctx, listAppSettings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AppSetting{}
	for rows.Next() {
		var i AppSetting
		if err := rows.Scan(&i.Key, &i.Value, &i.UpdatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setAppSetting = `-- name: SetAppSetting :one
INSERT INTO app_settings (
    key,
    value,
    updated_at
) VALUES (
    ?,
    ?,
    CURRENT_TIMESTAMP
) ON CONFLICT(key) DO UPDATE SET
    value = excluded.value,
    updated_at = CURRENT_TIMESTAMP
RETURNING "key", value, updated_at
`

type SetAppSettingParams struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

func (q *Queries) SetAppSetting(ctx context.Context, arg SetAppSettingParams) (AppSetting, error) {
	row := q.db.QueryRowContext(ctx, setAppSetting, arg.Key, arg.Value)
	var i AppSetting
	err := row.Scan(&i.Key, &i.Value, &i.UpdatedAt)
	return i, err
}
