// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth_profiles.sql

package db

import (
	"context"
	"database/sql"
)

const countAuthProfiles = `-- name: CountAuthProfiles :one
SELECT COUNT(*) FROM auth_profiles
`

func (q *Queries) CountAuthProfiles(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAuthProfiles)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAuthProfile = `-- name: CreateAuthProfile :one
INSERT INTO auth_profiles (
    name,
    auth_method,
    app_id,
    private_key_encrypted,
    token_encrypted
) VALUES (
    ?, ?, ?, ?, ?
) RETURNING id, name, auth_method, app_id, private_key_encrypted, token_encrypted, created_at, updated_at
`

type CreateAuthProfileParams struct {
	Name                string         `json:"name"`
	AuthMethod          string         `json:"auth_method"`
	AppID               sql.NullInt64  `json:"app_id"`
	PrivateKeyEncrypted sql.NullString `json:"private_key_encrypted"`
	TokenEncrypted      sql.NullString `json:"token_encrypted"`
}

func (q *Queries) CreateAuthProfile(ctx context.Context, arg CreateAuthProfileParams) (AuthProfile, error) {
	row := q.db.QueryRowContext(ctx, createAuthProfile,
		arg.Name,
		arg.AuthMethod,
		arg.AppID,
		arg.PrivateKeyEncrypted,
		arg.TokenEncrypted,
	)
	var i AuthProfile
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.AuthMethod,
		&i.AppID,
		&i.PrivateKeyEncrypted,
		&i.TokenEncrypted,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAuthProfile = `-- name: DeleteAuthProfile :exec
DELETE FROM auth_profiles
WHERE id = ?
`

func (q *Queries) DeleteAuthProfile(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteAuthProfile, id)
	return err
}

const getAuthProfileById = `-- name: GetAuthProfileById :one
SELECT id, name, auth_method, app_id, private_key_encrypted, token_encrypted, created_at, updated_at FROM auth_profiles
WHERE id = ? LIMIT 1
`

func (q *Queries) GetAuthProfileById(ctx context.Context, id int64) (AuthProfile, error) {
	row := q.db.QueryRowContext(ctx, getAuthProfileById, id)
	var i AuthProfile
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.AuthMethod,
		&i.AppID,
		&i.PrivateKeyEncrypted,
		&i.TokenEncrypted,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAuthProfileByName = `-- name: GetAuthProfileByName :one
SELECT id, name, auth_method, app_id, private_key_encrypted, token_encrypted, created_at, updated_at FROM auth_profiles
WHERE name = ? LIMIT 1
`

func (q *Queries) GetAuthProfileByName(ctx context.Context, name string) (AuthProfile, error) {
	row := q.db.QueryRowContext(ctx, getAuthProfileByName, name)
	var i AuthProfile
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.AuthMethod,
		&i.AppID,
		&i.PrivateKeyEncrypted,
		&i.TokenEncrypted,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAuthProfiles = `-- name: ListAuthProfiles :many
SELECT id, name, auth_method, app_id, private_key_encrypted, token_encrypted, created_at, updated_at FROM auth_profiles
ORDER BY name ASC
`

func (q *Queries) ListAuthProfiles(ctx context.Context) ([]AuthProfile, error) {
	rows, err := q.db.QueryContext(ctx, listAuthProfiles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuthProfile{}
	for rows.Next() {
		var i AuthProfile
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.AuthMethod,
			&i.AppID,
			&i.PrivateKeyEncrypted,
			&i.TokenEncrypted,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAuthProfile = `-- name: UpdateAuthProfile :one
UPDATE auth_profiles
SET name = ?,
    auth_method = ?,
    app_id = ?,
    private_key_encrypted = ?,
    token_encrypted = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?
RETURNING id, name, auth_method, app_id, private_key_encrypted, token_encrypted, created_at, updated_at
`

type UpdateAuthProfileParams struct {
	Name                string         `json:"name"`
	AuthMethod          string         `json:"auth_method"`
	AppID               sql.NullInt64  `json:"app_id"`
	PrivateKeyEncrypted sql.NullString `json:"private_key_encrypted"`
	TokenEncrypted      sql.NullString `json:"token_encrypted"`
	ID                  int64          `json:"id"`
}

func (q *Queries) UpdateAuthProfile(ctx context.Context, arg UpdateAuthProfileParams) (AuthProfile, error) {
	row := q.db.QueryRowContext(ctx, updateAuthProfile,
		arg.Name,
		arg.AuthMethod,
		arg.AppID,
		arg.PrivateKeyEncrypted,
		arg.TokenEncrypted,
		arg.ID,
	)
	var i AuthProfile
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.AuthMethod,
		&i.AppID,
		&i.PrivateKeyEncrypted,
		&i.TokenEncrypted,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
