// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: job_history.sql

package db

import (
	"context"
	"database/sql"
)

const countJobHistory = `-- name: CountJobHistory :one
SELECT COUNT(*) FROM job_history
`

func (q *Queries) CountJobHistory(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countJobHistory)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countJobHistoryByPoolId = `-- name: CountJobHistoryByPoolId :one
SELECT COUNT(*) FROM job_history
WHERE pool_id = ?
`

func (q *Queries) CountJobHistoryByPoolId(ctx context.Context, poolID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countJobHistoryByPoolId, poolID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createJobHistory = `-- name: CreateJobHistory :one
INSERT INTO job_history (
    pool_id,
    runner_name,
    status,
    queued_at,
    started_at,
    completed_at,
    log_retention_path
) VALUES (
    ?, ?, ?, ?, ?, ?, ?
) RETURNING id, pool_id, runner_name, status, queued_at, started_at, completed_at, log_retention_path, created_at
`

type CreateJobHistoryParams struct {
	PoolID           int64          `json:"pool_id"`
	RunnerName       string         `json:"runner_name"`
	Status           string         `json:"status"`
	QueuedAt         sql.NullTime   `json:"queued_at"`
	StartedAt        sql.NullTime   `json:"started_at"`
	CompletedAt      sql.NullTime   `json:"completed_at"`
	LogRetentionPath sql.NullString `json:"log_retention_path"`
}

func (q *Queries) CreateJobHistory(ctx context.Context, arg CreateJobHistoryParams) (JobHistory, error) {
	row := q.db.QueryRowContext(ctx, createJobHistory,
		arg.PoolID,
		arg.RunnerName,
		arg.Status,
		arg.QueuedAt,
		arg.StartedAt,
		arg.CompletedAt,
		arg.LogRetentionPath,
	)
	var i JobHistory
	err := row.Scan(
		&i.ID,
		&i.PoolID,
		&i.RunnerName,
		&i.Status,
		&i.QueuedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.LogRetentionPath,
		&i.CreatedAt,
	)
	return i, err
}

const deleteJobHistoryOlderThan = `-- name: DeleteJobHistoryOlderThan :exec
DELETE FROM job_history
WHERE completed_at < ?
`

func (q *Queries) DeleteJobHistoryOlderThan(ctx context.Context, completedAt sql.NullTime) error {
	_, err := q.db.ExecContext(ctx, deleteJobHistoryOlderThan, completedAt)
	return err
}

const getJobHistoryById = `-- name: GetJobHistoryById :one
SELECT id, pool_id, runner_name, status, queued_at, started_at, completed_at, log_retention_path, created_at FROM job_history
WHERE id = ? LIMIT 1
`

func (q *Queries) GetJobHistoryById(ctx context.Context, id int64) (JobHistory, error) {
	row := q.db.QueryRowContext(ctx, getJobHistoryById, id)
	var i JobHistory
	err := row.Scan(
		&i.ID,
		&i.PoolID,
		&i.RunnerName,
		&i.Status,
		&i.QueuedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.LogRetentionPath,
		&i.CreatedAt,
	)
	return i, err
}

const listJobHistory = `-- name: ListJobHistory :many
SELECT id, pool_id, runner_name, status, queued_at, started_at, completed_at, log_retention_path, created_at FROM job_history
ORDER BY id DESC
LIMIT ? OFFSET ?
`

type ListJobHistoryParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListJobHistory(ctx context.Context, arg ListJobHistoryParams) ([]JobHistory, error) {
	rows, err := q.db.QueryContext(ctx, listJobHistory, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []JobHistory{}
	for rows.Next() {
		var i JobHistory
		if err := rows.Scan(
			&i.ID,
			&i.PoolID,
			&i.RunnerName,
			&i.Status,
			&i.QueuedAt,
			&i.StartedAt,
			&i.CompletedAt,
			&i.LogRetentionPath,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJobHistoryByPoolId = `-- name: ListJobHistoryByPoolId :many
SELECT id, pool_id, runner_name, status, queued_at, started_at, completed_at, log_retention_path, created_at FROM job_history
WHERE pool_id = ?
ORDER BY id DESC
LIMIT ? OFFSET ?
`

type ListJobHistoryByPoolIdParams struct {
	PoolID int64 `json:"pool_id"`
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListJobHistoryByPoolId(ctx context.Context, arg ListJobHistoryByPoolIdParams) ([]JobHistory, error) {
	rows, err := q.db.QueryContext(ctx, listJobHistoryByPoolId, arg.PoolID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []JobHistory{}
	for rows.Next() {
		var i JobHistory
		if err := rows.Scan(
			&i.ID,
			&i.PoolID,
			&i.RunnerName,
			&i.Status,
			&i.QueuedAt,
			&i.StartedAt,
			&i.CompletedAt,
			&i.LogRetentionPath,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateJobHistoryStatus = `-- name: UpdateJobHistoryStatus :one
UPDATE job_history
SET status = ?,
    completed_at = ?,
    log_retention_path = ?
WHERE id = ?
RETURNING id, pool_id, runner_name, status, queued_at, started_at, completed_at, log_retention_path, created_at
`

type UpdateJobHistoryStatusParams struct {
	Status           string         `json:"status"`
	CompletedAt      sql.NullTime   `json:"completed_at"`
	LogRetentionPath sql.NullString `json:"log_retention_path"`
	ID               int64          `json:"id"`
}

func (q *Queries) UpdateJobHistoryStatus(ctx context.Context, arg UpdateJobHistoryStatusParams) (JobHistory, error) {
	row := q.db.QueryRowContext(ctx, updateJobHistoryStatus,
		arg.Status,
		arg.CompletedAt,
		arg.LogRetentionPath,
		arg.ID,
	)
	var i JobHistory
	err := row.Scan(
		&i.ID,
		&i.PoolID,
		&i.RunnerName,
		&i.Status,
		&i.QueuedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.LogRetentionPath,
		&i.CreatedAt,
	)
	return i, err
}
