// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: renovate_runs.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const completeRenovateRun = `-- name: CompleteRenovateRun :one
UPDATE renovate_runs
SET status = ?,
    completed_at = ?,
    summary = ?
WHERE id = ?
RETURNING id, pool_id, status, started_at, completed_at, summary, container_id, created_at
`

type CompleteRenovateRunParams struct {
	Status      string       `json:"status"`
	CompletedAt sql.NullTime `json:"completed_at"`
	Summary     string       `json:"summary"`
	ID          int64        `json:"id"`
}

func (q *Queries) CompleteRenovateRun(ctx context.Context, arg CompleteRenovateRunParams) (RenovateRun, error) {
	row := q.db.QueryRowContext(ctx, completeRenovateRun,
		arg.Status,
		arg.CompletedAt,
		arg.Summary,
		arg.ID,
	)
	var i RenovateRun
	err := row.Scan(
		&i.ID,
		&i.PoolID,
		&i.Status,
		&i.StartedAt,
		&i.CompletedAt,
		&i.Summary,
		&i.ContainerID,
		&i.CreatedAt,
	)
	return i, err
}

const completeRenovateRunByContainerID = `-- name: CompleteRenovateRunByContainerID :one
UPDATE renovate_runs
SET status = ?,
    completed_at = ?,
    summary = ?
WHERE container_id = ?
RETURNING id, pool_id, status, started_at, completed_at, summary, container_id, created_at
`

type CompleteRenovateRunByContainerIDParams struct {
	Status      string         `json:"status"`
	CompletedAt sql.NullTime   `json:"completed_at"`
	Summary     string         `json:"summary"`
	ContainerID sql.NullString `json:"container_id"`
}

func (q *Queries) CompleteRenovateRunByContainerID(ctx context.Context, arg CompleteRenovateRunByContainerIDParams) (RenovateRun, error) {
	row := q.db.QueryRowContext(ctx, completeRenovateRunByContainerID,
		arg.Status,
		arg.CompletedAt,
		arg.Summary,
		arg.ContainerID,
	)
	var i RenovateRun
	err := row.Scan(
		&i.ID,
		&i.PoolID,
		&i.Status,
		&i.StartedAt,
		&i.CompletedAt,
		&i.Summary,
		&i.ContainerID,
		&i.CreatedAt,
	)
	return i, err
}

const countRenovateRunsByPoolId = `-- name: CountRenovateRunsByPoolId :one
SELECT COUNT(*) FROM renovate_runs
WHERE pool_id = ?
`

func (q *Queries) CountRenovateRunsByPoolId(ctx context.Context, poolID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countRenovateRunsByPoolId, poolID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createRenovateRun = `-- name: CreateRenovateRun :one
INSERT INTO renovate_runs (
    pool_id,
    status,
    started_at,
    summary,
    container_id
) VALUES (
    ?, ?, ?, ?, ?
) RETURNING id, pool_id, status, started_at, completed_at, summary, container_id, created_at
`

type CreateRenovateRunParams struct {
	PoolID      int64          `json:"pool_id"`
	Status      string         `json:"status"`
	StartedAt   time.Time      `json:"started_at"`
	Summary     string         `json:"summary"`
	ContainerID sql.NullString `json:"container_id"`
}

func (q *Queries) CreateRenovateRun(ctx context.Context, arg CreateRenovateRunParams) (RenovateRun, error) {
	row := q.db.QueryRowContext(ctx, createRenovateRun,
		arg.PoolID,
		arg.Status,
		arg.StartedAt,
		arg.Summary,
		arg.ContainerID,
	)
	var i RenovateRun
	err := row.Scan(
		&i.ID,
		&i.PoolID,
		&i.Status,
		&i.StartedAt,
		&i.CompletedAt,
		&i.Summary,
		&i.ContainerID,
		&i.CreatedAt,
	)
	return i, err
}

const deleteRenovateRunsByPoolId = `-- name: DeleteRenovateRunsByPoolId :exec
DELETE FROM renovate_runs
WHERE pool_id = ?
`

func (q *Queries) DeleteRenovateRunsByPoolId(ctx context.Context, poolID int64) error {
	_, err := q.db.ExecContext(ctx, deleteRenovateRunsByPoolId, poolID)
	return err
}

const getLatestRenovateRunByPoolId = `-- name: GetLatestRenovateRunByPoolId :one
SELECT id, pool_id, status, started_at, completed_at, summary, container_id, created_at FROM renovate_runs
WHERE pool_id = ?
ORDER BY started_at DESC, id DESC
LIMIT 1
`

func (q *Queries) GetLatestRenovateRunByPoolId(ctx context.Context, poolID int64) (RenovateRun, error) {
	row := q.db.QueryRowContext(ctx, getLatestRenovateRunByPoolId, poolID)
	var i RenovateRun
	err := row.Scan(
		&i.ID,
		&i.PoolID,
		&i.Status,
		&i.StartedAt,
		&i.CompletedAt,
		&i.Summary,
		&i.ContainerID,
		&i.CreatedAt,
	)
	return i, err
}

const getRenovateRun = `-- name: GetRenovateRun :one
SELECT id, pool_id, status, started_at, completed_at, summary, container_id, created_at FROM renovate_runs
WHERE id = ? LIMIT 1
`

func (q *Queries) GetRenovateRun(ctx context.Context, id int64) (RenovateRun, error) {
	row := q.db.QueryRowContext(ctx, getRenovateRun, id)
	var i RenovateRun
	err := row.Scan(
		&i.ID,
		&i.PoolID,
		&i.Status,
		&i.StartedAt,
		&i.CompletedAt,
		&i.Summary,
		&i.ContainerID,
		&i.CreatedAt,
	)
	return i, err
}

const getRenovateRunByContainerID = `-- name: GetRenovateRunByContainerID :one
SELECT id, pool_id, status, started_at, completed_at, summary, container_id, created_at FROM renovate_runs
WHERE container_id = ? LIMIT 1
`

func (q *Queries) GetRenovateRunByContainerID(ctx context.Context, containerID sql.NullString) (RenovateRun, error) {
	row := q.db.QueryRowContext(ctx, getRenovateRunByContainerID, containerID)
	var i RenovateRun
	err := row.Scan(
		&i.ID,
		&i.PoolID,
		&i.Status,
		&i.StartedAt,
		&i.CompletedAt,
		&i.Summary,
		&i.ContainerID,
		&i.CreatedAt,
	)
	return i, err
}

const listRenovateRunsByPoolId = `-- name: ListRenovateRunsByPoolId :many
SELECT id, pool_id, status, started_at, completed_at, summary, container_id, created_at FROM renovate_runs
WHERE pool_id = ?
ORDER BY started_at DESC, id DESC
LIMIT ? OFFSET ?
`

type ListRenovateRunsByPoolIdParams struct {
	PoolID int64 `json:"pool_id"`
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListRenovateRunsByPoolId(ctx context.Context, arg ListRenovateRunsByPoolIdParams) ([]RenovateRun, error) {
	rows, err := q.db.QueryContext(ctx, listRenovateRunsByPoolId, arg.PoolID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RenovateRun{}
	for rows.Next() {
		var i RenovateRun
		if err := rows.Scan(
			&i.ID,
			&i.PoolID,
			&i.Status,
			&i.StartedAt,
			&i.CompletedAt,
			&i.Summary,
			&i.ContainerID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRenovateRunContainerID = `-- name: UpdateRenovateRunContainerID :exec
UPDATE renovate_runs
SET container_id = ?
WHERE id = ?
`

type UpdateRenovateRunContainerIDParams struct {
	ContainerID sql.NullString `json:"container_id"`
	ID          int64          `json:"id"`
}

func (q *Queries) UpdateRenovateRunContainerID(ctx context.Context, arg UpdateRenovateRunContainerIDParams) error {
	_, err := q.db.ExecContext(ctx, updateRenovateRunContainerID, arg.ContainerID, arg.ID)
	return err
}
