// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: renovate_configs.sql

package db

import (
	"context"
	"database/sql"
)

const createRenovateConfig = `-- name: CreateRenovateConfig :one
INSERT INTO renovate_configs (
    pool_id,
    enabled,
    cron_schedule,
    image
) VALUES (
    ?, ?, ?, ?
) RETURNING id, pool_id, enabled, cron_schedule, image, created_at, updated_at
`

type CreateRenovateConfigParams struct {
	PoolID       int64          `json:"pool_id"`
	Enabled      bool           `json:"enabled"`
	CronSchedule sql.NullString `json:"cron_schedule"`
	Image        string         `json:"image"`
}

func (q *Queries) CreateRenovateConfig(ctx context.Context, arg CreateRenovateConfigParams) (RenovateConfig, error) {
	row := q.db.QueryRowContext(ctx, createRenovateConfig,
		arg.PoolID,
		arg.Enabled,
		arg.CronSchedule,
		arg.Image,
	)
	var i RenovateConfig
	err := row.Scan(
		&i.ID,
		&i.PoolID,
		&i.Enabled,
		&i.CronSchedule,
		&i.Image,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteRenovateConfigByPoolId = `-- name: DeleteRenovateConfigByPoolId :exec
DELETE FROM renovate_configs
WHERE pool_id = ?
`

func (q *Queries) DeleteRenovateConfigByPoolId(ctx context.Context, poolID int64) error {
	_, err := q.db.ExecContext(ctx, deleteRenovateConfigByPoolId, poolID)
	return err
}

const getRenovateConfigByPoolId = `-- name: GetRenovateConfigByPoolId :one
SELECT id, pool_id, enabled, cron_schedule, image, created_at, updated_at FROM renovate_configs
WHERE pool_id = ? LIMIT 1
`

func (q *Queries) GetRenovateConfigByPoolId(ctx context.Context, poolID int64) (RenovateConfig, error) {
	row := q.db.QueryRowContext(ctx, getRenovateConfigByPoolId, poolID)
	var i RenovateConfig
	err := row.Scan(
		&i.ID,
		&i.PoolID,
		&i.Enabled,
		&i.CronSchedule,
		&i.Image,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEnabledRenovateConfigs = `-- name: ListEnabledRenovateConfigs :many
SELECT id, pool_id, enabled, cron_schedule, image, created_at, updated_at FROM renovate_configs
WHERE enabled = 1
ORDER BY pool_id ASC
`

func (q *Queries) ListEnabledRenovateConfigs(ctx context.Context) ([]RenovateConfig, error) {
	rows, err := q.db.QueryContext(ctx, listEnabledRenovateConfigs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RenovateConfig{}
	for rows.Next() {
		var i RenovateConfig
		if err := rows.Scan(
			&i.ID,
			&i.PoolID,
			&i.Enabled,
			&i.CronSchedule,
			&i.Image,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRenovateConfigs = `-- name: ListRenovateConfigs :many
SELECT id, pool_id, enabled, cron_schedule, image, created_at, updated_at FROM renovate_configs
ORDER BY pool_id ASC
`

func (q *Queries) ListRenovateConfigs(ctx context.Context) ([]RenovateConfig, error) {
	rows, err := q.db.QueryContext(ctx, listRenovateConfigs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RenovateConfig{}
	for rows.Next() {
		var i RenovateConfig
		if err := rows.Scan(
			&i.ID,
			&i.PoolID,
			&i.Enabled,
			&i.CronSchedule,
			&i.Image,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRenovateConfig = `-- name: UpdateRenovateConfig :one
UPDATE renovate_configs
SET enabled = ?,
    cron_schedule = ?,
    image = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE pool_id = ?
RETURNING id, pool_id, enabled, cron_schedule, image, created_at, updated_at
`

type UpdateRenovateConfigParams struct {
	Enabled      bool           `json:"enabled"`
	CronSchedule sql.NullString `json:"cron_schedule"`
	Image        string         `json:"image"`
	PoolID       int64          `json:"pool_id"`
}

func (q *Queries) UpdateRenovateConfig(ctx context.Context, arg UpdateRenovateConfigParams) (RenovateConfig, error) {
	row := q.db.QueryRowContext(ctx, updateRenovateConfig,
		arg.Enabled,
		arg.CronSchedule,
		arg.Image,
		arg.PoolID,
	)
	var i RenovateConfig
	err := row.Scan(
		&i.ID,
		&i.PoolID,
		&i.Enabled,
		&i.CronSchedule,
		&i.Image,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
